artifact_uri: file:///C:/credit-fraud-mlops/mlruns/357113965122247338/7f65e38ebac640679ebaccbaa64c3fb5/artifacts
end_time: 1758279131675
entry_point_name: ''
experiment_id: '357113965122247338'
lifecycle_stage: active
run_id: 7f65e38ebac640679ebaccbaa64c3fb5
run_name: random_forest_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1758279032029
status: 3
tags: []
user_id: 2-09
