artifact_uri: file:///C:/credit-fraud-mlops/mlruns/357113965122247338/6263c0bdb6ba4d71ad9f65acc09bebc3/artifacts
end_time: 1758276843594
entry_point_name: ''
experiment_id: '357113965122247338'
lifecycle_stage: active
run_id: 6263c0bdb6ba4d71ad9f65acc09bebc3
run_name: catboost_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1758276794017
status: 3
tags: []
user_id: 2-09
