channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - graphviz==0.21
  - lightgbm==4.6.0
  - matplotlib==3.10.6
  - numpy==2.3.3
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
