artifact_uri: mlflow-artifacts:/0/2a978cf89cfc46a09224dff1a8bbc555/artifacts
end_time: 1758154264358
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2a978cf89cfc46a09224dff1a8bbc555
run_name: classy-shrimp-477
source_name: ''
source_type: 4
source_version: ''
start_time: 1758154244464
status: 3
tags: []
user_id: 2-09
