aliases: []
creation_timestamp: 1758603297008
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1758603297008
metrics: null
model_id: m-567b549cfcce4deaab9fd032c4d56be9
name: champion_model
params: null
run_id: 9c3ae4d1ee17449382cdad0bba681ede
run_link: ''
source: file:///C:/credit-fraud-mlops/mlruns/357113965122247338/models/m-567b549cfcce4deaab9fd032c4d56be9/artifacts
status: READY
status_message: null
storage_location: file:///C:/credit-fraud-mlops/mlruns/357113965122247338/models/m-567b549cfcce4deaab9fd032c4d56be9/artifacts
user_id: null
version: 1
